layout:                # Admincentral -> Design
  groups:              #       Design -> Groups
    - name: content    #       Groups -> Group
      apps:            #        Group -> Apps
        - name: news   #         Apps -> Name
        - name: topics #         Apps -> Name
