!content-type:products   #   apps/news -> contentTypes/news

name: products           #        Name -> Internal
label: Products          #        Name -> Panel
enabled: true            #     Visible -> True
icon: icon-tasks-app     #        Icon -> Style

permissions:             # Permissions -> Handling
  roles:                 #       Roles -> Allowed
    superuser: superuser #   Superuser -> All
    editors: superuser   #     Editors -> All