# PLANTILLAS SELECCIONABLES
templates:                                                                        # Referencia -> Plantillas.
  class: info.magnolia.module.site.templates.ReferencingPrototypeTemplateSettings # Referencia -> Opciones.
  prototypeId: training-templating-website:pages/prototype                        # Referencia -> Path.
  availability:                                                                   # Referencia -> Disponibilidad.
    templates:                                                                    # Referencia -> Plantillas.
      home:                                                                       # Referencia -> Disponible.
        id: training-templating-website:pages/home                                # Referencia -> Path.
      default:                                                                    # Referencia -> Disponible.
        id: training-templating-website:pages/default                             # Referencia -> Path.

# IDIOMAS SELECCIONABLES
i18n:                                                                             # Referencia -> Idiomas.
  class: info.magnolia.cms.i18n.DefaultI18nContentSupport                         # Referencia -> Soportables.
  enabled: true                                                                   # Referencia -> i18n Activo.
  fallbackLocale: en                                                              # Referencia -> Predeterminado.
  locales:                                                                        # Referencia -> Disponibles.
    en:                                                                           # Referencia -> Etiqueta.
      country: ''                                                                 # Referencia -> Pais.
      enabled: true                                                               # Referencia -> Seleccionable.
      language: en                                                                # Referencia -> Idioma.
    de:
      country: ''
      enabled: true
      language: de
    fr:
      country: ''
      enabled: true
      language: fr
    it:
      country: ''
      enabled: true
      language: it

# 
theme:
  name: training-theme
 
## También definido en JCR. Es importante mostrar ambas posibilidades.
mappings:
  website:
    URIPrefix: ''
    handlePrefix: /training
    repository: website