cssFiles:
  bootstrap:
    media: screen
    addFingerPrint: true
    link: /.resources/training-templating-website/webresources/css/bootstrap.css

jsFiles:
  jquery.min.js:
    addFingerPrint: true
    link: /.resources/training-templating-website/webresources/js/jquery.min.js
  bootstrap.min.js:
    addFingerPrint: true
    link: /.resources/training-templating-website/webresources/js/bootstrap.min.js

imaging:
  class: info.magnolia.templating.imaging.VariationAwareImagingSupport
  variations:
    large:
      class: info.magnolia.templating.imaging.variation.SimpleResizeVariation
      width: 1600
    medium:
      class: info.magnolia.templating.imaging.variation.SimpleResizeVariation
      width: 800
    small:
      class: info.magnolia.templating.imaging.variation.SimpleResizeVariation
      width: 300
